# Generated by Django 4.2 on 2023-04-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_food_materialgoods_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialgoods',
            name='months_owned',
            field=models.IntegerField(default=0),
        ),
    ]
