# Generated by Django 4.1.6 on 2023-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_rename_user_usern"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="nothing", max_length=200)),
                ("last_name", models.CharField(default="nothing", max_length=200)),
                ("email", models.CharField(default="nothing", max_length=200)),
                ("username", models.CharField(default="nothing", max_length=200)),
                ("password", models.CharField(default="nothing", max_length=200)),
            ],
        ),
    ]
