# Generated by Django 4.1.6 on 2023-04-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_user"),
    ]

    operations = [
        migrations.DeleteModel(name="UserN",),
    ]
