# Generated by Django 4.2 on 2023-04-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_usern'),
        ('myapp', '0004_remove_user_name'),
    ]

    operations = [
    ]
